/* Automatically generated by '../src/build/bin/build-entry.vue' */

import Buttons from '../src/Buttons.vue'
import Cell from '../src/Cell.vue'
import Folder from '../src/Folder.vue'
import InputNum from '../src/InputNum.vue'
import Inputs from '../src/Inputs.vue'
import Loading from '../src/Loading.vue'
import Page from '../src/Page.vue'
import Popups from '../src/Popups.vue'
import ProgressBar from '../src/ProgressBar.vue'
import Stepbar from '../src/Stepbar.vue'
import Switchs from '../src/Switchs.vue'
import Tabbar from '../src/Tabbar.vue'
import Toast from '../src/Toast.vue'

module.exports = {
  Buttons,
  Cell,
  Folder,
  InputNum,
  Inputs,
  Loading,
  Page,
  Popups,
  ProgressBar,
  Stepbar,
  Switchs,
  Tabbar,
  Toast
}

module.exports.default = module.exports
